### PR TITLE
Hotfix/caching errors

### PR DESCRIPTION
**Pull request by mzajkowski**
We've experienced a ton of errors in the application log when LeBlender tried to reach cache values from items in the grid.editors.config.js files and we're storing them in the other package (to avoid overriding them at each Umbraco update for example).

I found that the code is not checking for situation with null or empty list when reading LeBlender editors and is trying to get the Config property straight from the null value.

I fixed it and while working with the helper class I just cleaned up the code a little bit and refactored some parts of it. Feel free to test it and merge it if it will be good for you.

### CODE REVIEW

**Comment by Bitmapped** [comment]
@mzajkowski It doesn't look like your code compiles. Can you check this and update your commits?

**Comment by mzajkowski** [comment]
Hi @Bitmapped, I finally found some time to check this. I pulled from the latest master, rebuilded it locally and it all works correctly. I haven't touched anything in my code.

Feel free to review and merge if you think it's all good.

**Comment by Bitmapped** [comment]
Hi @mzajkowski - thanks for checking. I just grabbed your code and it compiled cleanly for me in Visual Studio 2017. I'm not sure why it was throwing strange compile errors here on Github's automated build environment, but it's marked as compiling cleanly now.

Unfortunately, I don't have the rights to merge your code in. I came across your PR because I was having the same problem and one of the maintainers didn't like my proposed PR. Yours is a little more direct, so hopefully it'll go through now that it shows as compiling OK.

**Comment by mzajkowski** [comment]
@Bitmapped I fixed latest conflict which was produced by changes in the master branch. Let me know if you need anything else here nad merge/decline this PR as you wish.

**Comment by Bitmapped** [comment]
@mzajkowski Thanks for fixing things. Unfortunately, like I mentioned before, I don't have the ability to merge PRs myself. Hopefully @soreng can take a look since I believe he has the ability to do this.

**Comment by mzajkowski** [comment]
Argh, correct, don't know why I marked you, sorry :)

Maybe @agiraud can help?

**Pull request closed without merging**
